version: '3'
services:
  web:
    build:
      context: ./html
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0.33
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["mysqld", "--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
