version: '3'
services:
  web:
    build:
      context: ./html
      dockerfile: Dockerfile
    ports:
      - "8080:9000"
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0.33
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    driver: bridge
