version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
